### ISSUE TITLE
Common interface for files

### ISSUE THREAD

**Issue by JarekW** [fsi-open/doctrine-extensions#70]
It would be very helpful if all files from bundle extends from `\SplFileInfo`. If someone use this with symfony (doctrine-extensions-bundle) we could add return type hint in methods. Symfony [already extends from it](https://github.com/symfony/http-foundation/blob/master/File/File.php#L24) and \SplfileInfo doesnt need the file to exist:
>SplFileInfo::__construct( string $file_name )
>Creates a new SplFileInfo object for the file_name specified. The file does not need to exist, or be readable.

**Comment by szymach** [comment]
Our `File` class already [extends](https://github.com/fsi-open/doctrine-extensions/blob/master/lib/FSi/DoctrineExtensions/Uploadable/File.php#L12) a base class, so this gets tricky. `Gaufrette\File` has a different constructor than `\SplFileInfo`, so we would have to get around that somehow, or just abandon using that library altogether, but that is not a trivial task.

**Comment by chives** [comment]
The perfect solution is to add own abstraction layer for filesystem and implement first adapter for [flysystem](http://flysystem.thephpleague.com/) or something else if anyone has better idea
