### ISSUE TITLE
Allow setting translations via a single method

### ISSUE THREAD

**Issue by szymach** [fsi-open/doctrine-extensions#73]
Current implementation requires public access for modifying translated fields. This is troublesome in a situation, where you would like to only have read access to entity properties. We could add an option of setting the translation via a specified method, which would inject a populated translation object for the requested locale.

**Comment by JarekW** [comment]
Maybe we could set it as doctrine do, through reflection instead of property accessor?

**Comment by szymach** [comment]
Dropped in favour of switching to reflection
